pipeline {
  agent any

  environment {
    IMAGE_NAME = "bobieaditya03/myapp"
    DOCKER_CREDS = "dockerhub"
  }

  options {
    timestamps()
    buildDiscarder(logRotator(numToKeepStr: '10'))
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Read Version') {
      steps {
        script {
          VERSION = readFile('VERSION').trim()
          BUILD_TAG = "${VERSION}.${BUILD_NUMBER}"
        }
      }
    }

    stage('Build Image') {
      steps {
        script {
          docker.build(
            "${IMAGE_NAME}:${BUILD_TAG}",
            "--build-arg VERSION=${BUILD_TAG} ."
          )
        }
      }
    }

    stage('Push Image') {
      steps {
        script {
          docker.withRegistry('https://index.docker.io/v1/', DOCKER_CREDS) {
            def img = docker.image("${IMAGE_NAME}:${BUILD_TAG}")
            img.push()
            img.push("latest")
          }
        }
      }
    }

    stage('Verify Image') {
      steps {
        sh "docker pull ${IMAGE_NAME}:${BUILD_TAG}"
      }
    }
  }

  post {
    success {
      echo "✅ Image pushed: ${BUILD_TAG}"
    }
    failure {
      echo "❌ Pipeline gagal"
    }
  }
}