#!/bin/bash

# Setup script untuk GitHub Actions CI/CD
# Jalankan script ini untuk generate Secrets instruction

echo "================================"
echo "GitHub Actions Setup Guide"
echo "================================"
echo ""
echo "Step 1: Setup Docker Hub (Optional tapi recommended)"
echo "=================================================="
echo ""
echo "1. Go to: https://hub.docker.com"
echo "2. Login atau register"
echo "3. Navigate to: Profile → Account Settings → Security"
echo "4. Click: 'New Access Token'"
echo "5. Name: github-actions"
echo "6. Copy the generated token"
echo ""
echo ""
echo "Step 2: Add Secrets ke GitHub"
echo "=============================="
echo ""
echo "1. Go to GitHub Repository"
echo "2. Settings → Secrets and variables → Actions"
echo "3. Click: 'New repository secret'"
echo ""
echo "Add this secrets:"
echo "  Name: DOCKERHUB_USERNAME"
echo "  Value: [your docker hub username]"
echo ""
echo "  Name: DOCKERHUB_TOKEN"
echo "  Value: [token yang sudah di-copy dari Docker Hub]"
echo ""
echo ""
echo "Step 3: Push Code ke GitHub"
echo "==========================="
echo ""
echo "git add ."
echo "git commit -m 'Setup GitHub Actions CI/CD'"
echo "git push origin main"
echo ""
echo ""
echo "Step 4: Monitor Workflow"
echo "======================="
echo ""
echo "1. Go to: Repository → Actions"
echo "2. Lihat workflow yang sedang running"
echo "3. Tunggu sampai selesai"
echo "4. Cek image di registry:"
echo ""
echo "   - GitHub Container Registry:"
echo "     docker pull ghcr.io/[USERNAME]/vehicle-rental-app:latest"
echo ""
echo "   - Docker Hub:"
echo "     docker pull [DOCKERHUB_USERNAME]/vehicle-rental-app:latest"
echo ""
echo ""
echo "================================"
echo "Setup Selesai! 🎉"
echo "================================"
echo ""
echo "Dokumentasi lengkap ada di:"
echo "- CI-CD.md (Quick start - 5 menit)"
echo "- GITHUB-ACTIONS.md (Detailed guide)"
echo ""
